language: node_js
node_js:
  - "5"
  - "4"
  #- "4.1"
  #- "4.0"
env:
  global:
    - CXX=g++-4.8 debug='sql,lackey*'
    - PGPORT=5433
    - PGHOST=localhost
    - DATABASE_URL=postgres://localhost:5433/lackey-cms-test
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - precise-pgdg-9.5
    packages:
      - g++-4.8
      - postgresql-9.5
      - postgresql-contrib-9.5
  postgresql: 9.5
before_install:
  - $CXX --version
  - if [ "$TRAVIS_NODE_VERSION" = "0.8" ]; then npm install -g npm@2.7.3; fi;

# NPM
before_script:
  - sudo cp /etc/postgresql/9.4/main/pg_hba.conf /etc/postgresql/9.5/main/pg_hba.conf
  - sudo /etc/init.d/postgresql restart
  - psql -U postgres -c 'CREATE DATABASE "lackey-cms-test";'
  - npm install -g gulp
script: 'gulp test'
sudo: required
notifications:
  slack: enigma-marketing:yfkKsg1TfkVCvECHeeiLzq7Z
# nop
